import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";

const Layout = ({ children, paginas }) => {
  return (
    <div>
      <Head>
        <title>Mercado Clone - {paginas}</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;700;900&display=swap"
          rel="stylesheet"
        />
        <script src="https://kit.fontawesome.com/aeef59a78f.js" crossorigin="anonymous"></script>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/pngegg.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};

export default Layout;
